name: Upload to S3

on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Copy file to S3
        shell: bash
        env:
          aws_key_id: AKIARMD4UCXY7PRMTAFV
          aws_secret_access_key: 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
          aws_s3_bucket: ynov-globalressources
        run: |
          sudo apt-get update && sudo apt-get -y install awscli
          aws configure set aws_access_key_id $aws_key_id
          aws configure set aws_secret_access_key $aws_secret_access_key 
          aws configure set default.region eu-central-1
          aws s3 cp ./dist/ s3://ynov-globalressources/